#
# Resume
# CI Pipeline
#

on:
  push: {}
jobs:
  typeset-resume:
    name: Typeset Resume PDF
    runs-on: ubuntu-22.04
    outputs:
      resume_pdf: "${{ steps.filename.outputs.resume_pdf }}"
    steps:
    - uses: actions/checkout@v3
    - uses: WtfJoke/setup-tectonic@v2.1.0
      with:
        # needed for querying tectonic releases from github
        github-token: ${{ secrets.GITHUB_TOKEN }}
        tectonic-version: 0.12.0
    - name: Build Resume PDF
      run: |
        tectonic -X build
    - name: Derive Resume filename
      id: filename
      run: |
        set -ex -o pipefail
        # sed: strip prefix (eg. 'feat/') if any and replace filename unfriendly characters
        REF_SUFFIX="$(printf ${{ github.ref_name }} | sed -Ee 's|[[:alpha:]]+/||g; s|[/-]|_|g')"
        # rename resume file based on pushed ref.
        RESUME_PDF="zhu_zhanyan_resume_${REF_SUFFIX}.pdf"
        echo "resume_pdf=${RESUME_PDF}" >> "$GITHUB_OUTPUT"
    - name: Upload built PDF as Github Actions Artifact
      uses: actions/upload-artifact@v3
      with:
        name: "${{ steps.filename.outputs.resume_pdf }}"
        path: build/resume/resume.pdf
  
  preview-resume:
    name: Generate Resume Preview
    runs-on: ubuntu-22.04
    needs: typeset-resume
    defaults:
      run:
        working-directory: assets/previews
    env:
      RESUME_PDF: "${{ needs.preview-resume.outputs.resume_pdf }}"
    permissions:
      # needed for github-auto-commit-action to commit to repo.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download Resume PDF
        uses: actions/download-artifact@v3
        with:
          name: "${{ env.RESUME_PDF }}"
      - name: Generate PNG preview from PDF
        run: |
          set -ex -o pipefail
          sudo apt-get install pdftoppm
          RESUME_BASE="$(basename ${RESUME_PDF} .pdf)"
          pdftoppm -png "${RESUME_PDF}" "${RESUME_BASE}"
          echo "RESUME_PNG=${RESUME_BASE}-1.png" >> $GITHUB_ENV
      - name: Push Resume PNG preview to Github Pages
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          file_pattern: assets/previews/${{ env.RESUME_PNG }}
          commit_message: "chore: add/update resume preview for ${{ github.ref }}"
  
  spellcheck:
    name: Spellcheck Resume
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install codespell with Pip
      run: pip install -r requirements.txt
    - name: Perform spellcheck with codespell
      run: codespell
