#
# Resume
# CI Pipeline
#

on:
  push: {}
jobs:
  typeset-resume:
    runs-on: ubuntu-22.04
    name: Typeset Resume PDF
    steps:
    - uses: actions/checkout@v3
    - uses: WtfJoke/setup-tectonic@v2.1.0
      with:
        # needed for querying tectonic releases from github
        github-token: ${{ secrets.GITHUB_TOKEN }}
        tectonic-version: 0.12.0
    - name: Build Resume PDF
      run: |
        set -ex
        tectonic -X build
        # sed: strip prefix (eg. 'feat/') if any and replace filename unfriendly characters
        REF_SUFFIX="$(printf ${{ github.ref_name }} | sed -Ee 's|[[:alpha:]]+/||g; s|[/-]|_|g')"
        # rename resume file based on pushed ref.
        RESUME_PDF="zhu_zhanyan_resume_${REF_SUFFIX}.pdf"
        mv build/resume/resume.pdf "${RESUME_PDF}"
        echo "RESUME_PDF=${RESUME_PDF}" >> $GITHUB_ENV
    - name: Upload built PDF as Github Actions Artifact
      uses: actions/upload-artifact@v3
      with:
        path: "${{ env.RESUME_PDF }}"
  
  spellcheck:
    name: Spellcheck Resume
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install codespell with Pip
      run: pip install -r requirements.txt
    - name: Perform spellcheck with codespell
      run: codespell
